In [55]:
# import the relevant python libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [56]:
# load the dataset
# print the first five rows


df = pd.read_csv(r"C:\Users\yawasante\Desktop\all\data cleaning\using jupyter notebook\Uncleaned_DS_jobs.csv")
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [57]:
# we will drop the column index since pandas has built in index which does the same thing
df = df.drop('index', axis=1)
df.head(2)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

In [58]:
# for this cleaning exercise, we will drop the job description column

df = df.drop('Job Description', axis=1)
df.head(2)

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

In [59]:
# lets check our column names
# any column with space, lets fill it with an underscore

df.columns

Index(['Job Title', 'Salary Estimate', 'Rating', 'Company Name', 'Location',
       'Headquarters', 'Size', 'Founded', 'Type of ownership', 'Industry',
       'Sector', 'Revenue', 'Competitors'],
      dtype='str')

In [60]:
# job title, salary estimate, company name, type of ownership all have spaces in their names
# we will use list comprehension to fill it using the replace function

df.columns = [col.replace(' ','_') for col in df.columns]

# lets print our columns to confirm the changes
df.columns

Index(['Job_Title', 'Salary_Estimate', 'Rating', 'Company_Name', 'Location',
       'Headquarters', 'Size', 'Founded', 'Type_of_ownership', 'Industry',
       'Sector', 'Revenue', 'Competitors'],
      dtype='str')

## Exploratory Data Analysis

In [61]:
# check for the number of columns and rows
df.shape

(672, 13)

In [62]:
# we use the info function to have an overview of the dataset
# the data types, and whether there are missing values in any column

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job_Title          672 non-null    str
 1   Salary_Estimate    672 non-null    str
 2   Rating             672 non-null    float64
 3   Company_Name       672 non-null    str
 4   Location           672 non-null    str
 5   Headquarters       672 non-null    str
 6   Size               672 non-null    str
 7   Founded            672 non-null    int64
 8   Type_of_ownership  672 non-null    str
 9   Industry           672 non-null    str
 10  Sector             672 non-null    str
 11  Revenue            672 non-null    str
 12  Competitors        672 non-null    str
dtypes: float64(1), int64(1), str(11)
memory usage: 68.4 KB

In [63]:
# isnull and sum is also used to check for missing values
df.isnull().sum()

Job_Title            0
Salary_Estimate      0
Rating               0
Company_Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type_of_ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

In [64]:
# we use the describe function to check for the descriptive statistics of the numeric columns

df.describe()

           Rating      Founded
count  672.000000   672.000000
mean     3.518601  1635.529762
std      1.410329   756.746640
min     -1.000000    -1.000000
25%      3.300000  1917.750000
50%      3.800000  1995.000000
75%      4.300000  2009.000000
max      5.000000  2019.000000

# Lets start the data cleaning process
 using the info function and the isnull.sum creates the impression that there are no missing values.
 sometimes there are placeholder values.
 so we will check for that in some of the columns.

In [65]:
df.head(2)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

In [66]:
# we will use the value count function to check for the placeholder values
# we will do the data cleaning by doing it column by column
# after dealing with a column, we move on to the next column
# this is the format that we are going to use, which lets us focus on a column at a time

# we will start with the first column job title

df['Job_Title'].value_counts(dropna=False)

Job_Title
Data Scientist                                                      337
Data Engineer                                                        26
Senior Data Scientist                                                19
Machine Learning Engineer                                            16
Data Analyst                                                         12
                                                                   ...
Sr. Research Associate/ Scientist, NGS prep & Molecular Genomics      1
Developer III - Data Science                                          1
Hydrogen/Tritium Materials Scientist (Experienced)                    1
Data Scientist/Data Analytics Practitioner                            1
AI/ML - Machine Learning Scientist, Siri Understanding                1
Name: count, Length: 172, dtype: int64

for the job title, there is no a placeholder value, which means no missing values as well. the datatype is also ok

In [67]:
# the next column is the salary estimate column

df['Salary_Estimate'].value_counts(dropna=False)

Salary_Estimate
$75K-$131K (Glassdoor est.)     32
$79K-$131K (Glassdoor est.)     32
$99K-$132K (Glassdoor est.)     32
$137K-$171K (Glassdoor est.)    30
$90K-$109K (Glassdoor est.)     30
$56K-$97K (Glassdoor est.)      22
$79K-$106K (Glassdoor est.)     22
$90K-$124K (Glassdoor est.)     22
$101K-$165K (Glassdoor est.)    21
$91K-$150K (Glassdoor est.)     21
$122K-$146K (Glassdoor est.)    21
$112K-$116K (Glassdoor est.)    21
$110K-$163K (Glassdoor est.)    21
$124K-$198K (Glassdoor est.)    21
$69K-$116K (Glassdoor est.)     21
$95K-$119K (Glassdoor est.)     21
$212K-$331K (Glassdoor est.)    21
$128K-$201K (Glassdoor est.)    21
$138K-$158K (Glassdoor est.)    21
$92K-$155K (Glassdoor est.)     21
$141K-$225K (Glassdoor est.)    20
$145K-$225K(Employer est.)      20
$79K-$147K (Glassdoor est.)     20
$31K-$56K (Glassdoor est.)      20
$66K-$112K (Glassdoor est.)     20
$80K-$132K (Glassdoor est.)     20
$87K-$141K (Glassdoor est.)     20
$105K-$167K (Glassdoor est.)    20
$71K-$123K (Glassdoor est.)     19
$79K-$133K (Glassdoor est.)     19
Name: count, dtype: int64

There is also no placeholder in the salary estimate column. 
For this column will split it into minimum and maximum salary.
To do that, we will first remove the parenthesis and its content before splitting

In [68]:
# using the replace function to remove the parenthesis with the content
# this is a simple understanding way to do it
# lets use regex

pattern = r'\s*\([^)]*\)'

df['Salary_Estimate'] = df['Salary_Estimate'].str.replace(pattern,'', regex=True)
df['Salary_Estimate'].head()

0    $137K-$171K
1    $137K-$171K
2    $137K-$171K
3    $137K-$171K
4    $137K-$171K
Name: Salary_Estimate, dtype: str

In [69]:
# we strip the salary estimate column for any trailing spaces
df['Salary_Estimate'] = df['Salary_Estimate'].str.strip()
df.head(2)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K-$171K,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K,4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

In [70]:
# the next task is to split the columns using the '-' as the delimeter
# to do that, will add the two columns and assign the split of the salary estimate to them

df[['Min_Salary', 'Max_Salary']] = df['Salary_Estimate'].str.split('-', expand=True)
df.head(2)

,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary
0,Sr Data Scientist,$137K-$171K,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K
1,Data Scientist,$137K-$171K,4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K

The two columns have been added with the values. we can now drop the estimate column

In [71]:
df = df.drop('Salary_Estimate', axis=1)
df.head(2)

,Job_Title,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary
0,Sr Data Scientist,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K
1,Data Scientist,4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K

We are done with the task on the Salary estimate column which is now the min and max salary columns.

In [72]:
# Our next colum is the rating column but we can see that Company name column also has the ratings attached to it
# to resolve this, lets extract the rating in the company column and then decide on the one to use.

df[['Company', 'Ratings']] = df['Company_Name'].str.split('\n', expand=True)
df.head(2)

,Job_Title,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary,Company,Ratings
0,Sr Data Scientist,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K,Healthfirst,3.1
1,Data Scientist,4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K,ManTech,4.2

Now that we have the Rating column and Ratings from the company name, we can decide on which one to use. I will use the value count functions on the two columns

In [73]:
df['Rating'].value_counts()

Rating
 3.5    58
-1.0    50
 3.3    41
 4.0    41
 3.9    40
 3.8    39
 3.7    38
 5.0    36
 4.5    32
 3.6    31
 3.4    31
 4.2    29
 4.1    25
 4.4    24
 4.7    22
 3.2    21
 4.8    20
 2.9    14
 4.3    14
 3.1    12
 4.6    12
 4.9    11
 2.7    10
 3.0     7
 2.6     4
 2.8     3
 2.5     2
 2.2     1
 2.4     1
 2.3     1
 2.1     1
 2.0     1
Name: count, dtype: int64

In [74]:
df['Ratings'].value_counts()

Ratings
3.5    59
4.0    42
3.3    41
3.9    40
3.8    39
3.7    38
5.0    35
4.5    32
3.4    31
3.6    30
4.2    28
4.1    25
4.4    24
4.7    22
3.2    22
4.8    20
2.9    14
4.3    14
3.1    12
4.6    12
4.9    11
2.7    10
3.0     7
2.6     4
2.8     3
2.5     2
2.2     1
2.4     1
2.3     1
2.1     1
2.0     1
Name: count, dtype: int64

You will notice that, the Rating column in the dataset has a placeholder value of -1 but the Ratings column we extracted does not have any placeholder value. In this case we will use the Ratings column and drop the rating column and the company name column. Also, we have to change the data type which is an object to a float.

In [75]:
df = df.drop(['Rating','Company_Name'], axis=1)
df.head()

,Job_Title,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary,Company,Ratings
0,Sr Data Scientist,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K,Healthfirst,3.1
1,Data Scientist,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K,ManTech,4.2
2,Data Scientist,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,$137K,$171K,Analysis Group,3.8
3,Data Scientist,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",$137K,$171K,INFICON,3.5
4,Data Scientist,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",$137K,$171K,Affinity Solutions,2.9

In [76]:
df['Ratings'] = df['Ratings'].astype(float)
df['Ratings'].dtype

dtype('float64')

Next we will look at the Location column and Headquarters column to check for placeholder value

In [77]:
df['Location'].value_counts()

Location
San Francisco, CA    69
New York, NY         50
Washington, DC       26
Boston, MA           24
Chicago, IL          22
                     ..
Redmond, WA           1
West Chester, PA      1
Quantico, VA          1
Fort Lee, NJ          1
Irwindale, CA         1
Name: count, Length: 207, dtype: int64

In [78]:
df['Headquarters'].value_counts()

Headquarters
New York, NY         33
San Francisco, CA    31
-1                   31
Chicago, IL          23
Boston, MA           19
                     ..
Oakville, Canada      1
San Bruno, CA         1
West Chester, PA      1
Utica, MI             1
Fort Lee, NJ          1
Name: count, Length: 229, dtype: int64

The location column has no placeholder value but the headquarters column has a placeholder value. We will replace the -1 with not available.

In [79]:
# we will use a dictionary to replace all the -1 to unknown
search = {'-1': 'unknown'}

In [80]:
df['Headquarters'] = df['Headquarters'].replace(search)
df['Headquarters'].value_counts()

Headquarters
New York, NY         33
San Francisco, CA    31
unknown              31
Chicago, IL          23
Boston, MA           19
                     ..
Oakville, Canada      1
San Bruno, CA         1
West Chester, PA      1
Utica, MI             1
Fort Lee, NJ          1
Name: count, Length: 229, dtype: int64

In [81]:
df.head(2)

,Job_Title,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary,Company,Ratings
0,Sr Data Scientist,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K,Healthfirst,3.1
1,Data Scientist,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K,ManTech,4.2

Next column to deal with is the Size column. we will look at the founded column as well

In [82]:
df['Size'].value_counts()

Size
51 to 200 employees        135
1001 to 5000 employees     104
1 to 50 employees           86
201 to 500 employees        85
10000+ employees            80
501 to 1000 employees       77
5001 to 10000 employees     61
-1                          27
Unknown                     17
Name: count, dtype: int64

In [83]:
df['Founded'].value_counts()

Founded
-1       118
 2012     34
 2011     25
 2010     22
 1996     22
        ...
 1977      1
 1896      1
 1972      1
 1949      1
 1962      1
Name: count, Length: 103, dtype: int64

Both columns have a placeholder value. we will replace them with not available. For the founded column, you can check also online and fill them as such.

In [84]:
df['Size'].dtype

In [85]:
df['Founded'].dtype

dtype('int64')

In [86]:
df['Size'] = df['Size'].replace(search)
df['Size'].value_counts()

Size
51 to 200 employees        135
1001 to 5000 employees     104
1 to 50 employees           86
201 to 500 employees        85
10000+ employees            80
501 to 1000 employees       77
5001 to 10000 employees     61
unknown                     27
Unknown                     17
Name: count, dtype: int64

In [87]:
df['Size'] = df['Size'].str.replace('Unknown','unknown')
df['Size'].value_counts()

Size
51 to 200 employees        135
1001 to 5000 employees     104
1 to 50 employees           86
201 to 500 employees        85
10000+ employees            80
501 to 1000 employees       77
5001 to 10000 employees     61
unknown                     44
Name: count, dtype: int64

In [88]:

df['Size'].value_counts()

Size
51 to 200 employees        135
1001 to 5000 employees     104
1 to 50 employees           86
201 to 500 employees        85
10000+ employees            80
501 to 1000 employees       77
5001 to 10000 employees     61
unknown                     44
Name: count, dtype: int64

In [89]:
df['Founded'] = df['Founded'].replace(-1, np.nan)
df['Founded'].value_counts(dropna=False)

Founded
NaN       118
2012.0     34
2011.0     25
2010.0     22
1996.0     22
         ...
1977.0      1
1896.0      1
1972.0      1
1949.0      1
1962.0      1
Name: count, Length: 103, dtype: int64

We will leave the NaN values as it is. You can either fill it with zero or whatever is desirable.

In [90]:
df['Founded'] = df['Founded'].astype('Int64')
df['Founded'].dtype

Int64Dtype()

In [91]:
df.head(2)

,Job_Title,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary,Company,Ratings
0,Sr Data Scientist,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K,Healthfirst,3.1
1,Data Scientist,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,$137K,$171K,ManTech,4.2

Since the column data types of type of ownership, industry, sector, revenue and competitors are the same, we will deal with placeholders as such.

In [92]:
# there is an Unknow value in the type of ownership column, so we will replace the placeholder value with that.
df['Type_of_ownership'].value_counts()

Type_of_ownership
Company - Private                 397
Company - Public                  153
Nonprofit Organization             36
Subsidiary or Business Segment     28
-1                                 27
Government                         10
Other Organization                  5
Private Practice / Firm             4
Unknown                             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64

In [93]:
df['Type_of_ownership'] = df['Type_of_ownership'].replace(search)
df['Type_of_ownership'].value_counts()

Type_of_ownership
Company - Private                 397
Company - Public                  153
Nonprofit Organization             36
Subsidiary or Business Segment     28
unknown                            27
Government                         10
Other Organization                  5
Private Practice / Firm             4
Unknown                             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64

In [94]:
df['Type_of_ownership'] = df['Type_of_ownership'].str.replace('Unknown','unknown')
df['Type_of_ownership'].value_counts()

Type_of_ownership
Company - Private                 397
Company - Public                  153
Nonprofit Organization             36
unknown                            31
Subsidiary or Business Segment     28
Government                         10
Other Organization                  5
Private Practice / Firm             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64

In [95]:
df['Industry'].value_counts()

Industry
-1                                          71
Biotech & Pharmaceuticals                   66
IT Services                                 61
Computer Hardware & Software                57
Aerospace & Defense                         46
Enterprise Software & Network Solutions     43
Consulting                                  38
Staffing & Outsourcing                      36
Insurance Carriers                          28
Internet                                    27
Advertising & Marketing                     23
Health Care Services & Hospitals            21
Research & Development                      17
Federal Agencies                            16
Investment Banking & Asset Management       13
Banks & Credit Unions                        8
Lending                                      8
Energy                                       5
Consumer Products Manufacturing              5
Telecommunications Services                  5
Insurance Agencies & Brokerages              4
Food & Beverage Manufacturing                4
Electrical & Electronic Manufacturing        3
Chemical Manufacturing                       3
Utilities                                    3
Industrial Manufacturing                     3
Video Games                                  3
Real Estate                                  3
Miscellaneous Manufacturing                  3
Architectural & Engineering Services         3
Other Retail Stores                          3
Colleges & Universities                      3
Accounting                                   3
Wholesale                                    3
Consumer Electronics & Appliances Stores     2
Express Delivery Services                    2
Venture Capital & Private Equity             2
Oil & Gas Services                           2
Transportation Equipment Manufacturing       2
Financial Transaction Processing             2
Timber Operations                            2
Travel Agencies                              2
Construction                                 2
Health, Beauty, & Fitness                    2
Shipping                                     1
Cable, Internet & Telephone Providers        1
Telecommunications Manufacturing             1
Transportation Management                    1
News Outlet                                  1
Food & Beverage Stores                       1
Hotels, Motels, & Resorts                    1
State & Regional Agencies                    1
Logistics & Supply Chain                     1
Farm Support Services                        1
Social Assistance                            1
Department, Clothing, & Shoe Stores          1
Publishing                                   1
Rail                                         1
Name: count, dtype: int64

In [96]:
# we will replace the placeholder with unknown

df['Industry'] = df['Industry'].replace(search)
df['Industry'].value_counts()

Industry
unknown                                     71
Biotech & Pharmaceuticals                   66
IT Services                                 61
Computer Hardware & Software                57
Aerospace & Defense                         46
Enterprise Software & Network Solutions     43
Consulting                                  38
Staffing & Outsourcing                      36
Insurance Carriers                          28
Internet                                    27
Advertising & Marketing                     23
Health Care Services & Hospitals            21
Research & Development                      17
Federal Agencies                            16
Investment Banking & Asset Management       13
Banks & Credit Unions                        8
Lending                                      8
Energy                                       5
Consumer Products Manufacturing              5
Telecommunications Services                  5
Insurance Agencies & Brokerages              4
Food & Beverage Manufacturing                4
Electrical & Electronic Manufacturing        3
Chemical Manufacturing                       3
Utilities                                    3
Industrial Manufacturing                     3
Video Games                                  3
Real Estate                                  3
Miscellaneous Manufacturing                  3
Architectural & Engineering Services         3
Other Retail Stores                          3
Colleges & Universities                      3
Accounting                                   3
Wholesale                                    3
Consumer Electronics & Appliances Stores     2
Express Delivery Services                    2
Venture Capital & Private Equity             2
Oil & Gas Services                           2
Transportation Equipment Manufacturing       2
Financial Transaction Processing             2
Timber Operations                            2
Travel Agencies                              2
Construction                                 2
Health, Beauty, & Fitness                    2
Shipping                                     1
Cable, Internet & Telephone Providers        1
Telecommunications Manufacturing             1
Transportation Management                    1
News Outlet                                  1
Food & Beverage Stores                       1
Hotels, Motels, & Resorts                    1
State & Regional Agencies                    1
Logistics & Supply Chain                     1
Farm Support Services                        1
Social Assistance                            1
Department, Clothing, & Shoe Stores          1
Publishing                                   1
Rail                                         1
Name: count, dtype: int64

In [97]:
df['Sector'].value_counts()

Sector
Information Technology                188
Business Services                     120
-1                                     71
Biotech & Pharmaceuticals              66
Aerospace & Defense                    46
Finance                                33
Insurance                              32
Manufacturing                          23
Health Care                            21
Government                             17
Oil, Gas, Energy & Utilities           10
Retail                                  7
Telecommunications                      7
Transportation & Logistics              6
Media                                   5
Real Estate                             3
Travel & Tourism                        3
Agriculture & Forestry                  3
Education                               3
Accounting & Legal                      3
Construction, Repair & Maintenance      2
Consumer Services                       2
Non-Profit                              1
Name: count, dtype: int64

In [98]:
df['Sector'] = df['Sector'].replace(search)

df['Sector'].value_counts()

Sector
Information Technology                188
Business Services                     120
unknown                                71
Biotech & Pharmaceuticals              66
Aerospace & Defense                    46
Finance                                33
Insurance                              32
Manufacturing                          23
Health Care                            21
Government                             17
Oil, Gas, Energy & Utilities           10
Retail                                  7
Telecommunications                      7
Transportation & Logistics              6
Media                                   5
Real Estate                             3
Travel & Tourism                        3
Agriculture & Forestry                  3
Education                               3
Accounting & Legal                      3
Construction, Repair & Maintenance      2
Consumer Services                       2
Non-Profit                              1
Name: count, dtype: int64

In [99]:
df['Revenue'].value_counts()

Revenue
Unknown / Non-Applicable            213
$100 to $500 million (USD)           94
$10+ billion (USD)                   63
$2 to $5 billion (USD)               45
$10 to $25 million (USD)             41
$1 to $2 billion (USD)               36
$25 to $50 million (USD)             36
$50 to $100 million (USD)            31
$1 to $5 million (USD)               31
-1                                   27
$500 million to $1 billion (USD)     19
$5 to $10 million (USD)              14
Less than $1 million (USD)           14
$5 to $10 billion (USD)               8
Name: count, dtype: int64

In [100]:
# the revenue column has unknown/non applicable so we will replace the placeholder with that
df['Revenue'] = df['Revenue'].str.replace('-1', 'Unknown / Non-Applicable')
df['Revenue'].value_counts()

Revenue
Unknown / Non-Applicable            240
$100 to $500 million (USD)           94
$10+ billion (USD)                   63
$2 to $5 billion (USD)               45
$10 to $25 million (USD)             41
$1 to $2 billion (USD)               36
$25 to $50 million (USD)             36
$50 to $100 million (USD)            31
$1 to $5 million (USD)               31
$500 million to $1 billion (USD)     19
$5 to $10 million (USD)              14
Less than $1 million (USD)           14
$5 to $10 billion (USD)               8
Name: count, dtype: int64

In [101]:
df['Competitors'].value_counts()

Competitors
-1                                                             501
Roche, GlaxoSmithKline, Novartis                                10
Leidos, CACI International, Booz Allen Hamilton                  6
Los Alamos National Laboratory, Battelle, SRI International      6
Commerce Signals, Cardlytics, Yodlee                             3
                                                              ...
United Natural Foods, US Foods, DPI Specialty Foods              1
LivePerson, Salesforce, SAP                                      1
Zurich Insurance, AXA XL, Allianz                                1
CSC, ManTech, SAIC                                               1
Genomic Health, Myriad Genetics, The Broad Institute             1
Name: count, Length: 108, dtype: int64

In [102]:
df['Competitors'] = df['Competitors'].replace(search)
df['Competitors'].value_counts()

Competitors
unknown                                                        501
Roche, GlaxoSmithKline, Novartis                                10
Leidos, CACI International, Booz Allen Hamilton                  6
Los Alamos National Laboratory, Battelle, SRI International      6
Commerce Signals, Cardlytics, Yodlee                             3
                                                              ...
United Natural Foods, US Foods, DPI Specialty Foods              1
LivePerson, Salesforce, SAP                                      1
Zurich Insurance, AXA XL, Allianz                                1
CSC, ManTech, SAIC                                               1
Genomic Health, Myriad Genetics, The Broad Institute             1
Name: count, Length: 108, dtype: int64

In [103]:
df.head(2)

,Job_Title,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors,Min_Salary,Max_Salary,Company,Ratings
0,Sr Data Scientist,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",$137K,$171K,Healthfirst,3.1
1,Data Scientist,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),unknown,$137K,$171K,ManTech,4.2

# We have done all the necessary manipulation of the dataset. we will now rearrange the column headers

In [104]:
cols_arranged = ['Job_Title','Min_Salary', 'Max_Salary','Company', 'Ratings', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type_of_ownership', 'Industry', 'Sector', 'Revenue', 'Competitors']
df = df[cols_arranged]
df.head()

,Job_Title,Min_Salary,Max_Salary,Company,Ratings,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors
0,Sr Data Scientist,$137K,$171K,Healthfirst,3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K,$171K,ManTech,4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),unknown
2,Data Scientist,$137K,$171K,Analysis Group,3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),unknown
3,Data Scientist,$137K,$171K,INFICON,3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K,$171K,Affinity Solutions,2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [105]:
df['Ratings'].value_counts(dropna=False)

Ratings
3.5    59
NaN    50
4.0    42
3.3    41
3.9    40
3.8    39
3.7    38
5.0    35
4.5    32
3.4    31
3.6    30
4.2    28
4.1    25
4.4    24
4.7    22
3.2    22
4.8    20
2.9    14
4.3    14
3.1    12
4.6    12
4.9    11
2.7    10
3.0     7
2.6     4
2.8     3
2.5     2
2.2     1
2.4     1
2.3     1
2.1     1
2.0     1
Name: count, dtype: int64

In [106]:
# there nan values in the ratings column.
# we will fill it with the median value

df.describe()

          Ratings      Founded
count  622.000000        554.0
mean     3.878457  1984.104693
std      0.609732    40.653609
min      2.000000       1781.0
25%      3.500000       1974.0
50%      3.800000       1999.0
75%      4.375000       2010.0
max      5.000000       2019.0

In [107]:
df['Ratings'] = df['Ratings'].fillna(df['Ratings'].median())
df['Ratings'].value_counts()

Ratings
3.8    89
3.5    59
4.0    42
3.3    41
3.9    40
3.7    38
5.0    35
4.5    32
3.4    31
3.6    30
4.2    28
4.1    25
4.4    24
4.7    22
3.2    22
4.8    20
2.9    14
4.3    14
3.1    12
4.6    12
4.9    11
2.7    10
3.0     7
2.6     4
2.8     3
2.5     2
2.2     1
2.4     1
2.3     1
2.1     1
2.0     1
Name: count, dtype: int64

In [108]:
df.shape

(672, 14)

In [109]:
# checking for duplicates

df[df.duplicated()]

,Job_Title,Min_Salary,Max_Salary,Company,Ratings,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,Sector,Revenue,Competitors
135,Machine Learning Engineer,$90K,$109K,Triplebyte,3.2,Remote,"San Francisco, CA",51 to 200 employees,2015,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,unknown
136,Senior Data Engineer,$90K,$109K,Lendio,4.9,"Lehi, UT","Lehi, UT",201 to 500 employees,2011,Company - Private,Lending,Finance,$50 to $100 million (USD),unknown
358,Data Scientist,$122K,$146K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
359,Data Scientist,$122K,$146K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
360,Data Scientist,$122K,$146K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
361,Data Scientist,$122K,$146K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
362,Data Scientist,$122K,$146K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
389,Data Scientist,$110K,$163K,HireAi,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
496,Data Scientist,$95K,$119K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
497,Data Scientist,$95K,$119K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
498,Data Scientist,$95K,$119K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
499,Data Scientist,$95K,$119K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown
500,Data Scientist,$95K,$119K,Hatch Data Inc,3.8,"San Francisco, CA",unknown,unknown,<NA>,unknown,unknown,unknown,Unknown / Non-Applicable,unknown

In [110]:
# we drop the duplicates

df = df.drop_duplicates()
df.shape

(659, 14)

In [111]:
# we will now save the file to csv 

# df.to_csv('cleaned_job_posting.csv', index=False)